services:
  - type: web
    name: magistro-darbas
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GUNICORN_TIMEOUT
        value: 120